name: Prepare publication

on:
  push:
    branches: [master]

env:
  NODE_VERSION: "22"

jobs:
  deploy-demo:
    if: github.repository_owner == 'zestedesavoir'
    name: Deploy the live demo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install local dependencies
        run: npm ci

      - name: Build the demo
        run: npm run build-demo

      - name: GitHub Push
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./packages/zmarkdown/public
          github_token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
